---
title: VtResist
timezone: UTC
collections:
  contacts:
    title: Contacts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: contacts
  values:
    layout: contact
email: resistancevermont@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
tagline: Show up, Speak out, Join in.
baseurl: ''
url: ''
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
